lr: 0.001
seed: 1
if_cuda: False
gamma: 0.5
log_dir: 'logs/' #_cube_2d/'
train_batch: 512
val_batch: 256
test_batch: 256
num_workers: 8
model_name: 'encoder-decoder-64'
input_type: 'step'
data_filepath: './data/'
dataset: 'cube_2d/video1'
lr_schedule: [20, 50, 100, 300]
num_gpus: 1
epochs: 1000